# My name is Bleander Ronoh
print("Byee Buddy")
print("Byee Friend")
print("Byee Pal")
print("Byee Mate")
print("Byee Friend")
print("Byee Pal")
print("Byee Mate")
print("Byee Pal")
print("Byee Mate")
print("Byee Friend")
print("Byee Pal")
print("Byee Mate")
print("Byee Friend")
print("Byee Pal")
print("Byee Mate")